import type {
  ChannelConnection,
  Customer,
  ExternalReference,
  PerformanceSnapshot,
} from "@/lib/yseo/types";

const baseNow = new Date("2026-04-08T09:00:00+09:00");

function hoursAgo(value: number) {
  return new Date(baseNow.getTime() - value * 60 * 60 * 1000).toISOString();
}

function daysAgo(value: number) {
  return new Date(baseNow.getTime() - value * 24 * 60 * 60 * 1000).toISOString();
}

export const customers: Customer[] = [
  {
    id: "owol-ent",
    name: "오월이비인후과",
    segment: "지역 병원",
    primaryManager: "민지",
    statusTag: "긴급 조치",
    onboardingStatus: "active",
    reportingProfile: "주간",
    memoSummary: "랜딩 교체 직후 파워링크 전환이 급격히 흔들렸습니다.",
    focus: "전환 급감 원인 분리와 일반 키워드 bid 방어",
    priorityRank: 1,
    nextReviewAt: hoursAgo(-3),
    lastActionAt: hoursAgo(2),
    channels: ["naver-searchad", "search-console"],
  },
  {
    id: "brickton-pilates",
    name: "브릭톤 필라테스",
    segment: "로컬 스튜디오",
    primaryManager: "태훈",
    statusTag: "오늘 점검",
    onboardingStatus: "active",
    reportingProfile: "주간",
    memoSummary: "오전 시간대 과소진과 저효율 adgroup이 겹칩니다.",
    focus: "예산 재배분과 시간대별 입찰 차등안 검토",
    priorityRank: 2,
    nextReviewAt: hoursAgo(-5),
    lastActionAt: hoursAgo(20),
    channels: ["naver-searchad", "business-profile"],
  },
  {
    id: "damyeon-clinic",
    name: "담연한의원",
    segment: "병원",
    primaryManager: "소연",
    statusTag: "관찰",
    onboardingStatus: "active",
    reportingProfile: "격주",
    memoSummary: "브랜디드 외 쿼리 CTR이 완만하게 하락 중입니다.",
    focus: "CTR 하락 원인이 제목/설명 노출인지 확인",
    priorityRank: 3,
    nextReviewAt: hoursAgo(-18),
    lastActionAt: daysAgo(2),
    channels: ["naver-searchad", "search-console"],
  },
  {
    id: "growing-pet",
    name: "그로잉펫",
    segment: "이커머스",
    primaryManager: "지후",
    statusTag: "정상",
    onboardingStatus: "active",
    reportingProfile: "월간",
    memoSummary: "주요 키워드군과 브랜드 검색이 모두 안정적입니다.",
    focus: "정상 유지",
    priorityRank: 6,
    nextReviewAt: daysAgo(-4),
    lastActionAt: daysAgo(4),
    channels: ["naver-searchad"],
  },
  {
    id: "lindoor-studio",
    name: "린도어 스튜디오",
    segment: "웨딩 촬영",
    primaryManager: "민지",
    statusTag: "오늘 점검",
    onboardingStatus: "active",
    reportingProfile: "주간",
    memoSummary: "검색 콘솔 recent data가 불완전하고 랜딩 1개가 급감했습니다.",
    focus: "incomplete 데이터 보정 이후 URL inspection 재확인",
    priorityRank: 4,
    nextReviewAt: hoursAgo(-8),
    lastActionAt: daysAgo(1),
    channels: ["naver-searchad", "search-console"],
  },
  {
    id: "osol-dental",
    name: "오솔길치과",
    segment: "치과",
    primaryManager: "태훈",
    statusTag: "긴급 조치",
    onboardingStatus: "active",
    reportingProfile: "주간",
    memoSummary: "네이버 sync가 제한 창에 걸려 오늘 데이터가 비었습니다.",
    focus: "sync 복구와 전날 성과 보정",
    priorityRank: 1,
    nextReviewAt: hoursAgo(-1),
    lastActionAt: hoursAgo(6),
    channels: ["naver-searchad", "business-profile"],
  },
  {
    id: "h-bike",
    name: "에이치바이크",
    segment: "로컬 리테일",
    primaryManager: "소연",
    statusTag: "관찰",
    onboardingStatus: "active",
    reportingProfile: "격주",
    memoSummary: "경쟁 키워드 CPC가 서서히 상승하지만 전환은 유지 중입니다.",
    focus: "CPC 상승 구간만 골라 방어",
    priorityRank: 5,
    nextReviewAt: daysAgo(-2),
    lastActionAt: daysAgo(1),
    channels: ["naver-searchad"],
  },
  {
    id: "garden-flower",
    name: "더가든 플라워",
    segment: "소상공인",
    primaryManager: "지후",
    statusTag: "정상",
    onboardingStatus: "active",
    reportingProfile: "월간",
    memoSummary: "검색 광고와 리뷰 반응이 모두 안정적입니다.",
    focus: "정상 유지",
    priorityRank: 7,
    nextReviewAt: daysAgo(-6),
    lastActionAt: daysAgo(3),
    channels: ["naver-searchad", "business-profile"],
  },
];

export const channelConnections: ChannelConnection[] = [
  {
    id: "conn-owol-naver",
    customerId: "owol-ent",
    channelType: "naver-searchad",
    connectionStatus: "connected",
    authMethod: "api-key",
    externalAccountRef: "cust-6102841",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(0.6),
    syncStatus: "succeeded",
    syncHeadline: "34분 전 핵심 성과와 adgroup 통계 수집 완료",
  },
  {
    id: "conn-owol-gsc",
    customerId: "owol-ent",
    channelType: "search-console",
    connectionStatus: "connected",
    authMethod: "oauth",
    externalAccountRef: "property",
    externalPropertyRef: "sc-domain:owolent.co.kr",
    tokenStatus: "valid",
    lastSyncAt: hoursAgo(4),
    syncStatus: "succeeded",
    syncHeadline: "오늘 새벽 D-3 보정 수집 완료",
  },
  {
    id: "conn-brickton-naver",
    customerId: "brickton-pilates",
    channelType: "naver-searchad",
    connectionStatus: "attention",
    authMethod: "api-key",
    externalAccountRef: "cust-6173290",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(1.5),
    lastErrorCode: "NAVER_SYNC_WINDOW_WARN",
    syncStatus: "succeeded",
    syncHeadline: "입찰 데이터는 수집됐지만 예산 필드 1건 누락",
  },
  {
    id: "conn-brickton-gbp",
    customerId: "brickton-pilates",
    channelType: "business-profile",
    connectionStatus: "attention",
    authMethod: "oauth",
    externalAccountRef: "accounts/194203812",
    externalPropertyRef: "locations/83920114",
    tokenStatus: "expiring",
    lastSyncAt: daysAgo(1),
    lastErrorCode: "GBP_REFRESH_EXPIRING",
    syncStatus: "failed",
    syncHeadline: "리뷰 동기화가 어제 이후 멈췄습니다.",
  },
  {
    id: "conn-damyeon-naver",
    customerId: "damyeon-clinic",
    channelType: "naver-searchad",
    connectionStatus: "connected",
    authMethod: "api-key",
    externalAccountRef: "cust-6021885",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(2),
    syncStatus: "succeeded",
    syncHeadline: "2시간 전 성과 집계 완료",
  },
  {
    id: "conn-damyeon-gsc",
    customerId: "damyeon-clinic",
    channelType: "search-console",
    connectionStatus: "connected",
    authMethod: "oauth",
    externalAccountRef: "property",
    externalPropertyRef: "https://damyeonclinic.kr/",
    tokenStatus: "valid",
    lastSyncAt: hoursAgo(7),
    syncStatus: "succeeded",
    syncHeadline: "새벽 property 수집 완료",
  },
  {
    id: "conn-growing-naver",
    customerId: "growing-pet",
    channelType: "naver-searchad",
    connectionStatus: "connected",
    authMethod: "api-key",
    externalAccountRef: "cust-6238801",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(3),
    syncStatus: "succeeded",
    syncHeadline: "정상 동기화",
  },
  {
    id: "conn-lindoor-naver",
    customerId: "lindoor-studio",
    channelType: "naver-searchad",
    connectionStatus: "connected",
    authMethod: "api-key",
    externalAccountRef: "cust-6120024",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(1.2),
    syncStatus: "succeeded",
    syncHeadline: "방금 성과 수집 완료",
  },
  {
    id: "conn-lindoor-gsc",
    customerId: "lindoor-studio",
    channelType: "search-console",
    connectionStatus: "attention",
    authMethod: "oauth",
    externalAccountRef: "property",
    externalPropertyRef: "sc-domain:lindoor.kr",
    tokenStatus: "valid",
    lastSyncAt: hoursAgo(9),
    lastErrorCode: "GSC_INCOMPLETE_RECENT",
    syncStatus: "succeeded",
    syncHeadline: "recent data incomplete 상태로 보정 대기",
  },
  {
    id: "conn-osol-naver",
    customerId: "osol-dental",
    channelType: "naver-searchad",
    connectionStatus: "blocked",
    authMethod: "api-key",
    externalAccountRef: "cust-6045588",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(11),
    lastErrorCode: "NAVER_429_WINDOW",
    syncStatus: "failed",
    syncHeadline: "429 제한 창에 걸려 금일 snapshot이 비었습니다.",
  },
  {
    id: "conn-osol-gbp",
    customerId: "osol-dental",
    channelType: "business-profile",
    connectionStatus: "connected",
    authMethod: "oauth",
    externalAccountRef: "accounts/208481920",
    externalPropertyRef: "locations/19240111",
    tokenStatus: "valid",
    lastSyncAt: daysAgo(1),
    syncStatus: "succeeded",
    syncHeadline: "리뷰와 위치 성과 수집 완료",
  },
  {
    id: "conn-hbike-naver",
    customerId: "h-bike",
    channelType: "naver-searchad",
    connectionStatus: "connected",
    authMethod: "api-key",
    externalAccountRef: "cust-6197731",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(5),
    syncStatus: "succeeded",
    syncHeadline: "오전 수집 완료",
  },
  {
    id: "conn-garden-naver",
    customerId: "garden-flower",
    channelType: "naver-searchad",
    connectionStatus: "connected",
    authMethod: "api-key",
    externalAccountRef: "cust-6290011",
    tokenStatus: "not-applicable",
    lastSyncAt: hoursAgo(6),
    syncStatus: "succeeded",
    syncHeadline: "정상 동기화",
  },
  {
    id: "conn-garden-gbp",
    customerId: "garden-flower",
    channelType: "business-profile",
    connectionStatus: "connected",
    authMethod: "oauth",
    externalAccountRef: "accounts/200484100",
    externalPropertyRef: "locations/44012009",
    tokenStatus: "valid",
    lastSyncAt: hoursAgo(20),
    syncStatus: "succeeded",
    syncHeadline: "리뷰 2건 반영 완료",
  },
];

export const externalReferences: ExternalReference[] = channelConnections.map(
  (connection) => ({
    id: `xref-${connection.id}`,
    channelConnectionId: connection.id,
    externalType:
      connection.channelType === "search-console"
        ? "property"
        : connection.channelType === "business-profile"
          ? "location"
          : "customer",
    externalId: connection.externalPropertyRef ?? connection.externalAccountRef,
    externalName: connection.externalPropertyRef ?? connection.externalAccountRef,
    parentExternalId: connection.externalAccountRef,
  }),
);

export const performanceSnapshots: PerformanceSnapshot[] = [
  {
    id: "snap-owol-naver-7d",
    customerId: "owol-ent",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "owol-ent",
    dateBucket: "7d",
    metricSetJson: {
      spend: 1280000,
      clicks: 1684,
      conversions: 41,
      ctr: 4.2,
      cpa: 31220,
      change7d: -28.4,
      summary: "일반 키워드 전환이 랜딩 교체 이후 급감",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(0.6),
  },
  {
    id: "snap-owol-gsc-7d",
    customerId: "owol-ent",
    channelType: "search-console",
    entityType: "customer",
    entityId: "owol-ent",
    dateBucket: "7d",
    metricSetJson: {
      clicks: 792,
      impressions: 19210,
      ctr: 4.1,
      avgPosition: 6.8,
      change7d: -11.2,
      summary: "비브랜디드 랜딩 2개 클릭 급감",
    },
    completenessState: "partial",
    capturedAt: hoursAgo(4),
  },
  {
    id: "snap-brickton-naver-7d",
    customerId: "brickton-pilates",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "brickton-pilates",
    dateBucket: "7d",
    metricSetJson: {
      spend: 870000,
      clicks: 1304,
      conversions: 29,
      ctr: 5.1,
      cpa: 30000,
      change7d: -12.9,
      summary: "오전 시간대 예산 과소진으로 오후 전환 손실",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(1.5),
  },
  {
    id: "snap-damyeon-naver-7d",
    customerId: "damyeon-clinic",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "damyeon-clinic",
    dateBucket: "7d",
    metricSetJson: {
      spend: 640000,
      clicks: 1012,
      conversions: 22,
      ctr: 4.8,
      cpa: 29090,
      change7d: -4.2,
      summary: "광고 성과는 안정적이지만 CTR이 서서히 하락",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(2),
  },
  {
    id: "snap-damyeon-gsc-7d",
    customerId: "damyeon-clinic",
    channelType: "search-console",
    entityType: "customer",
    entityId: "damyeon-clinic",
    dateBucket: "7d",
    metricSetJson: {
      clicks: 438,
      impressions: 12300,
      ctr: 3.6,
      avgPosition: 8.4,
      change7d: -6.1,
      summary: "브랜디드 외 쿼리 CTR이 2주 연속 하락",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(7),
  },
  {
    id: "snap-growing-naver-7d",
    customerId: "growing-pet",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "growing-pet",
    dateBucket: "7d",
    metricSetJson: {
      spend: 1510000,
      clicks: 2422,
      conversions: 64,
      ctr: 5.8,
      cpa: 23593,
      change7d: 3.2,
      summary: "브랜드와 일반 키워드 모두 안정",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(3),
  },
  {
    id: "snap-lindoor-naver-7d",
    customerId: "lindoor-studio",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "lindoor-studio",
    dateBucket: "7d",
    metricSetJson: {
      spend: 920000,
      clicks: 1108,
      conversions: 18,
      ctr: 3.7,
      cpa: 51111,
      change7d: -9.7,
      summary: "상위 랜딩 1개의 클릭 회복이 지연 중",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(1.2),
  },
  {
    id: "snap-lindoor-gsc-7d",
    customerId: "lindoor-studio",
    channelType: "search-console",
    entityType: "customer",
    entityId: "lindoor-studio",
    dateBucket: "7d",
    metricSetJson: {
      clicks: 254,
      impressions: 8020,
      ctr: 3.1,
      avgPosition: 9.7,
      change7d: -15.6,
      summary: "recent data incomplete, 확정 전 추세만 관찰",
    },
    completenessState: "partial",
    capturedAt: hoursAgo(9),
  },
  {
    id: "snap-osol-naver-7d",
    customerId: "osol-dental",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "osol-dental",
    dateBucket: "7d",
    metricSetJson: {
      spend: 0,
      clicks: 0,
      conversions: 0,
      ctr: 0,
      cpa: 0,
      change7d: -100,
      summary: "당일 snapshot 누락. 전일 데이터 재수집 필요",
    },
    completenessState: "estimated",
    capturedAt: hoursAgo(11),
  },
  {
    id: "snap-hbike-naver-7d",
    customerId: "h-bike",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "h-bike",
    dateBucket: "7d",
    metricSetJson: {
      spend: 770000,
      clicks: 1184,
      conversions: 20,
      ctr: 4.5,
      cpa: 38500,
      change7d: -3.8,
      summary: "경쟁 키워드 CPC만 상승 중",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(5),
  },
  {
    id: "snap-garden-naver-7d",
    customerId: "garden-flower",
    channelType: "naver-searchad",
    entityType: "customer",
    entityId: "garden-flower",
    dateBucket: "7d",
    metricSetJson: {
      spend: 420000,
      clicks: 804,
      conversions: 17,
      ctr: 5.6,
      cpa: 24705,
      change7d: 4.9,
      summary: "광고 성과 안정",
    },
    completenessState: "complete",
    capturedAt: hoursAgo(6),
  },
];
