import type {
  ChannelInsight,
  InternalMemo,
  Issue,
  ReportDraft,
  Suggestion,
  TaskExecution,
} from "@/lib/yseo/types";

const baseNow = new Date("2026-04-08T09:00:00+09:00");

function hoursAgo(value: number) {
  return new Date(baseNow.getTime() - value * 60 * 60 * 1000).toISOString();
}

function daysAgo(value: number) {
  return new Date(baseNow.getTime() - value * 24 * 60 * 60 * 1000).toISOString();
}

export const issues: Issue[] = [
  {
    id: "issue-001",
    customerId: "owol-ent",
    channelType: "naver-searchad",
    issueType: "conversion-drop",
    severity: "critical",
    detectedAt: hoursAgo(1),
    sourceSnapshotIds: ["snap-owol-naver-7d"],
    title: "파워링크 전환이 최근 7일 기준 28.4% 하락",
    summary: "랜딩 교체 이후 일반 키워드 전환이 빠르게 꺾였습니다.",
    recommendedAction: "일반 키워드 bid 방어와 랜딩 영향 분리",
    status: "open",
    dedupeKey: "owol-ent:conversion-drop",
  },
  {
    id: "issue-002",
    customerId: "brickton-pilates",
    channelType: "naver-searchad",
    issueType: "budget-balance",
    severity: "high",
    detectedAt: hoursAgo(3),
    sourceSnapshotIds: ["snap-brickton-naver-7d"],
    title: "오전 과소진으로 오후 전환 기회가 줄었습니다.",
    summary: "상위 adgroup 2개가 오전에 예산을 먼저 소진했습니다.",
    recommendedAction: "시간대별 입찰과 예산 재배분 검토",
    status: "open",
    dedupeKey: "brickton-pilates:budget-balance",
  },
  {
    id: "issue-003",
    customerId: "damyeon-clinic",
    channelType: "search-console",
    issueType: "ctr-soft-drop",
    severity: "medium",
    detectedAt: hoursAgo(10),
    sourceSnapshotIds: ["snap-damyeon-gsc-7d"],
    title: "브랜디드 쿼리 CTR이 완만하게 하락 중입니다.",
    summary: "2주 연속 CTR이 3%대 초반으로 내려가고 있습니다.",
    recommendedAction: "제목과 설명 수정 요청 초안 생성",
    status: "open",
    dedupeKey: "damyeon-clinic:ctr-soft-drop",
  },
  {
    id: "issue-004",
    customerId: "lindoor-studio",
    channelType: "search-console",
    issueType: "incomplete-data",
    severity: "high",
    detectedAt: hoursAgo(7),
    sourceSnapshotIds: ["snap-lindoor-gsc-7d"],
    title: "recent data incomplete 상태입니다.",
    summary: "최근 3일 데이터는 보정 전이므로 긴급 확정으로 보기 어렵습니다.",
    recommendedAction: "D-3 재수집 후 URL inspection 확인",
    status: "open",
    dedupeKey: "lindoor-studio:incomplete-data",
  },
  {
    id: "issue-005",
    customerId: "osol-dental",
    channelType: "naver-searchad",
    issueType: "sync-blocked",
    severity: "critical",
    detectedAt: hoursAgo(2),
    sourceSnapshotIds: ["snap-osol-naver-7d"],
    title: "네이버 sync가 429 제한 창에 걸렸습니다.",
    summary: "오늘 수집 결과가 비어 있어 운영 판단이 막힌 상태입니다.",
    recommendedAction: "느린 큐 전환과 최근 3일 재수집",
    status: "open",
    dedupeKey: "osol-dental:sync-blocked",
  },
  {
    id: "issue-006",
    customerId: "h-bike",
    channelType: "naver-searchad",
    issueType: "cpc-up",
    severity: "medium",
    detectedAt: hoursAgo(8),
    sourceSnapshotIds: ["snap-hbike-naver-7d"],
    title: "경쟁 키워드 CPC가 완만하게 상승 중입니다.",
    summary: "전환은 유지되지만 수익성이 낮아지고 있습니다.",
    recommendedAction: "급등 키워드만 선별해 하향 제안",
    status: "open",
    dedupeKey: "h-bike:cpc-up",
  },
];

export const suggestions: Suggestion[] = [
  {
    id: "sg-001",
    issueId: "issue-001",
    customerId: "owol-ent",
    channelType: "naver-searchad",
    suggestionType: "bid-adjustment",
    title: "일반 키워드 bid 8% 하향, 브랜드 키워드는 유지",
    summary: "전환이 꺾인 일반 키워드만 방어적으로 조정합니다.",
    payloadPreview: [
      "일반 키워드 6개 bid -8%",
      "브랜드 키워드 3개 유지",
      "랜딩 교체 후 48시간만 적용",
    ],
    rationaleText:
      "랜딩 영향과 입찰 영향이 섞여 있으므로 전체 하향보다 일반 키워드 분리가 안전합니다.",
    approvalStatus: "pending",
    riskLevel: "guarded",
  },
  {
    id: "sg-002",
    issueId: "issue-001",
    customerId: "owol-ent",
    channelType: "naver-searchad",
    suggestionType: "pause-candidates",
    title: "고비용 무전환 키워드 6개 pause 후보 생성",
    summary: "자동 실행 없이 검토용 후보만 만듭니다.",
    payloadPreview: ["고비용 키워드 6개", "pause 후 24시간 추적 권고"],
    rationaleText:
      "운영자가 최종 pause를 결정하도록 후보만 생성하는 흐름이 안전합니다.",
    approvalStatus: "pending",
    riskLevel: "manual",
  },
  {
    id: "sg-003",
    issueId: "issue-002",
    customerId: "brickton-pilates",
    channelType: "naver-searchad",
    suggestionType: "budget-redistribution",
    title: "오전 과소진 adgroup 예산 재배분",
    summary: "오전 과소진 group에서 오후 성과 group으로 이동합니다.",
    payloadPreview: ["오전 과소진 adgroup 2개 -12%", "오후 전환 adgroup 1개 +15%"],
    rationaleText:
      "총예산을 늘리기보다 내부 배분을 먼저 정리하는 편이 안정적입니다.",
    approvalStatus: "pending",
    riskLevel: "guarded",
  },
  {
    id: "sg-004",
    issueId: "issue-003",
    customerId: "damyeon-clinic",
    channelType: "search-console",
    suggestionType: "seo-request-draft",
    title: "CTR 하락 페이지 제목과 설명 수정 요청 초안",
    summary: "직접 수정이 아니라 요청 초안만 만듭니다.",
    payloadPreview: ["/m-treatment/traffic 제목 후보 3안", "설명문 2안 작성"],
    rationaleText:
      "Search Console은 직접 수정 도구가 아니므로 운영 요청 초안이 현실적입니다.",
    approvalStatus: "pending",
    riskLevel: "safe",
  },
  {
    id: "sg-005",
    issueId: "issue-004",
    customerId: "lindoor-studio",
    channelType: "search-console",
    suggestionType: "delayed-review",
    title: "D-3 보정 수집 이후 최종 판단으로 보류",
    summary: "긴급 확정 전에 recent incomplete를 먼저 걷어냅니다.",
    payloadPreview: ["내일 오전 재수집 예약", "inspection 결과 확인"],
    rationaleText:
      "incomplete 데이터를 사실처럼 해석하지 않기 위한 보수적 흐름입니다.",
    approvalStatus: "approved",
    riskLevel: "safe",
    approvedBy: "민지",
  },
  {
    id: "sg-006",
    issueId: "issue-005",
    customerId: "osol-dental",
    channelType: "naver-searchad",
    suggestionType: "sync-recovery",
    title: "느린 sync queue로 전환 후 최근 3일 재수집",
    summary: "429 제한 회피와 보정 수집을 동시에 처리합니다.",
    payloadPreview: ["RelKwdStat 호출 제거", "최근 3일 재수집", "sync blocked 해제 전 확인"],
    rationaleText:
      "자동 반복보다 운영자 확인 후 재시도하는 편이 안전합니다.",
    approvalStatus: "pending",
    riskLevel: "manual",
  },
  {
    id: "sg-007",
    issueId: "issue-006",
    customerId: "h-bike",
    channelType: "naver-searchad",
    suggestionType: "cpc-guardrail",
    title: "CPC 급등 키워드만 6% 하향",
    summary: "전환 유지 구간은 그대로 두고 급등 구간만 방어합니다.",
    payloadPreview: ["경쟁 키워드 4개 -6%", "브랜드 키워드는 유지"],
    rationaleText:
      "전체 하향보다 전환 훼손 가능성이 낮습니다.",
    approvalStatus: "executed",
    riskLevel: "guarded",
    approvedBy: "수연",
    executedAt: hoursAgo(16),
  },
];

export const reportDrafts: ReportDraft[] = [
  {
    id: "report-owol-0408",
    customerId: "owol-ent",
    periodStart: "2026-04-01",
    periodEnd: "2026-04-07",
    title: "오월이비인후과 주간 초안",
    summary:
      "랜딩 교체 이후 일반 키워드 전환이 급감해 이번 주에는 원인 분리와 bid 방어가 핵심입니다.",
    highlights: [
      "파워링크 전환 -28.4%",
      "브랜드 쿼리는 상대적으로 안정",
      "비브랜디드 랜딩 2개 클릭 급감",
    ],
    nextActions: ["일반 키워드 bid 8% 하향 검토", "고비용 키워드 pause 후보 6개 검토"],
    sourceSummaryJson: { channels: ["naver-searchad", "search-console"] },
    updatedAt: hoursAgo(1),
  },
  {
    id: "report-brickton-0408",
    customerId: "brickton-pilates",
    periodStart: "2026-04-01",
    periodEnd: "2026-04-07",
    title: "브릭톤 필라테스 주간 초안",
    summary:
      "오전 과소진이 성과 저하로 이어져 시간대별 예산과 입찰 배분이 핵심 과제입니다.",
    highlights: [
      "오전 과소진 adgroup 2개 발견",
      "오후 전환 구간 배분 재검토 필요",
      "GBP 리뷰 답글 토큰 만료 임박",
    ],
    nextActions: ["예산 재배분안 승인 검토", "GBP 토큰 갱신 여부 확인"],
    sourceSummaryJson: { channels: ["naver-searchad", "business-profile"] },
    updatedAt: hoursAgo(4),
  },
  {
    id: "report-lindoor-0408",
    customerId: "lindoor-studio",
    periodStart: "2026-04-01",
    periodEnd: "2026-04-07",
    title: "린도어 스튜디오 주간 초안",
    summary:
      "Search Console recent data가 incomplete 상태라 긴급 판단보다 보정 수집 이후 재검토가 우선입니다.",
    highlights: [
      "랜딩 1개 클릭 급감 추세",
      "recent data incomplete",
      "광고 성과는 아직 방어 가능",
    ],
    nextActions: ["D-3 재수집", "inspection 확인"],
    sourceSummaryJson: { channels: ["naver-searchad", "search-console"] },
    updatedAt: hoursAgo(6),
  },
];

export const taskExecutions: TaskExecution[] = [
  {
    id: "log-001",
    customerId: "h-bike",
    suggestionId: "sg-007",
    actionType: "keyword-bid-adjustment",
    actorType: "operator",
    actorName: "수연",
    resultStatus: "done",
    externalRequestRef: "naver:req:202604071700",
    summary: "CPC 급등 키워드 4개 bid -6% 적용",
    executedAt: hoursAgo(16),
  },
  {
    id: "log-002",
    customerId: "owol-ent",
    actionType: "landing-review",
    actorType: "operator",
    actorName: "민지",
    resultStatus: "queued",
    summary: "랜딩 교체 영향 메모를 남기고 리포트 초안 재생성",
    executedAt: hoursAgo(3),
  },
  {
    id: "log-003",
    customerId: "osol-dental",
    actionType: "sync-retry",
    actorType: "system",
    actorName: "YSEO Sync",
    resultStatus: "failed",
    externalRequestRef: "naver:req:202604080400",
    summary: "429 제한으로 즉시 재시도 실패, 느린 큐 이동 필요",
    executedAt: hoursAgo(5),
  },
  {
    id: "log-004",
    customerId: "brickton-pilates",
    actionType: "report-draft",
    actorType: "system",
    actorName: "YSEO Report",
    resultStatus: "done",
    summary: "주간 리포트 초안 생성 완료",
    executedAt: hoursAgo(4),
  },
];

export const internalMemos: InternalMemo[] = [
  {
    id: "memo-001",
    customerId: "owol-ent",
    body: "원장님 쪽에서 랜딩 문구를 자주 바꾸므로 전환 급감 시 랜딩 변경 이력을 먼저 확인합니다.",
    memoType: "context",
    createdBy: "민지",
    createdAt: daysAgo(6),
  },
  {
    id: "memo-002",
    customerId: "osol-dental",
    body: "RelKwdStat는 꼭 필요할 때만 돌리고 기본 sync에서는 제외하는 편이 안전합니다.",
    memoType: "risk",
    createdBy: "서현",
    createdAt: daysAgo(3),
  },
  {
    id: "memo-003",
    customerId: "lindoor-studio",
    body: "Search Console recent data가 incomplete일 때는 고객에게 긴급 확정으로 바로 전달하지 않습니다.",
    memoType: "handoff",
    createdBy: "민지",
    createdAt: daysAgo(2),
  },
];

export const channelInsights: ChannelInsight[] = [
  {
    id: "ins-001",
    customerId: "owol-ent",
    channelType: "naver-searchad",
    freshnessLabel: "34분 전",
    headline: "일반 키워드 전환이 랜딩 교체 이후 빠르게 꺾였습니다.",
    note: "브랜드 키워드는 비교적 안정적이라 전체 하향보다 분리 조정이 적합합니다.",
    metrics: [
      { label: "7일 클릭", value: "1,684", delta: "-18%", tone: "down" },
      { label: "7일 전환", value: "41", delta: "-28%", tone: "down" },
      { label: "CPA", value: "31,220원", delta: "+26%", tone: "down" },
    ],
  },
  {
    id: "ins-002",
    customerId: "owol-ent",
    channelType: "search-console",
    freshnessLabel: "오늘 수집",
    headline: "비브랜디드 랜딩 2개의 클릭이 함께 감소했습니다.",
    note: "recent data가 partial이라 최종 판단 전 보정 수집이 필요합니다.",
    metrics: [
      { label: "7일 클릭", value: "792", delta: "-11%", tone: "down" },
      { label: "CTR", value: "4.1%", delta: "-0.6%p", tone: "down" },
      { label: "평균 순위", value: "6.8", delta: "+0.4", tone: "down" },
    ],
  },
  {
    id: "ins-003",
    customerId: "brickton-pilates",
    channelType: "naver-searchad",
    freshnessLabel: "1시간 30분 전",
    headline: "오전 과소진 adgroup이 오후 전환 기회를 갉아먹고 있습니다.",
    note: "총예산 증액보다 시간대별 배분이 먼저입니다.",
    metrics: [
      { label: "7일 클릭", value: "1,304", delta: "-9%", tone: "down" },
      { label: "전환", value: "29", delta: "-13%", tone: "down" },
      { label: "CTR", value: "5.1%", delta: "+0.3%p", tone: "up" },
    ],
  },
  {
    id: "ins-004",
    customerId: "damyeon-clinic",
    channelType: "search-console",
    freshnessLabel: "7시간 전",
    headline: "브랜디드 쿼리 CTR이 완만하게 떨어지고 있습니다.",
    note: "긴급 수준은 아니지만 제목과 설명 수정 요청 초안을 준비할 시점입니다.",
    metrics: [
      { label: "7일 클릭", value: "438", delta: "-6%", tone: "down" },
      { label: "CTR", value: "3.6%", delta: "-0.4%p", tone: "down" },
      { label: "평균 순위", value: "8.4", delta: "+0.1", tone: "flat" },
    ],
  },
  {
    id: "ins-005",
    customerId: "lindoor-studio",
    channelType: "search-console",
    freshnessLabel: "9시간 전",
    headline: "최근 3일 데이터가 incomplete 상태라 긴급 판단을 막아두는 편이 맞습니다.",
    note: "YSEO는 이 구간을 경고로 올리되 자동 확정하지 않습니다.",
    metrics: [
      { label: "7일 클릭", value: "254", delta: "-15%", tone: "down" },
      { label: "CTR", value: "3.1%", delta: "-0.5%p", tone: "down" },
      { label: "데이터 상태", value: "partial" },
    ],
  },
  {
    id: "ins-006",
    customerId: "osol-dental",
    channelType: "naver-searchad",
    freshnessLabel: "11시간 전",
    headline: "오늘 snapshot이 비어 있어 성과 판단보다 복구가 먼저입니다.",
    note: "429 제한 회피를 위한 느린 큐 분리가 필요합니다.",
    metrics: [
      { label: "오늘 클릭", value: "0", delta: "-100%", tone: "down" },
      { label: "오늘 전환", value: "0", delta: "-100%", tone: "down" },
      { label: "상태", value: "sync blocked" },
    ],
  },
];
